language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- ls -la
- ls ~/.ssh/
- echo $GCE_SERVICE_ACCOUNT_EMAIL
- echo $GCE_CREDENTIALS_FILE
- echo $GCE_PROJECT_ID
env:
  global:
  - secure: o5sVl6Ob47ZEzJP8zcFX/tF1NUlZ4+I1R9b+PuTEO47QpLZKnG0/dzo8p1HxFGUNvpljmI3GyO5Ni1RWKNwJfYCaFjZDlue0ca2h7eotFtsFvkUT3Z5GJgZ3MB8gacNYPdyDMUg/hGolYUqERpWPNEC2bwBZiCB1RWZkb4e0+EZmqcuPAtbWSHl9Qvz1vCLQC8cWViPp3Xe1EnMbegvB6DH2ki1CzIcvMUZw7ueH4oKrCOJOJuu0kRBAIxaf7dUmbTi4HQrIrAhluLRHYUPM3b/1eF/RKLG4r41gT/t8jv9ViskUcYJcdm/7uhsUNhIRCriPGdvgAIEnzFaNL9HXPtymvOsKpLVpr7BMoc/+3db/+lf8y+eH9q1jbkGqiqLr0y3PF7XDwpRzDuZlrUA1fS9+kTzzfgOzKxYkxUZ6fubgBCWa6q+/hfmccbsoDLdWpf2JYp+rxV+ygeSI/xt7ydJc/I+KN5D7f7AYdpp6DpvNPQTfMSIes/R27pSybnn08Qgchb/O2fksf2O6JicHraaDtBeFVjupdfK4eNOXAhD/RHLSXvhc165aWEq+J8vYw5It7ar9Kw5JacSS0JZpJtR9zC5+tY3ZKTAqK7K2F/aNrCBlKUjMq02bDaNnnje2o7qSTyZDhm8m0GZJedlbpfkDJAJ06cTFSEEVgZsxiSA=
  - secure: oSPYFyNn+qGUZ1reKXFkmMVT9vf5+dGO3Q0/g+d04ak4lJ6wwXBOzDrVC12TMPABO4kmxVJz2Pt/4Lp3Iv5q+aW4k2AwS+0xYgrKRhx3nrSNOl0MGk4apu6OewiwPxBqnWTQLytffZL/PcitYb5h/JltDK5eDNgDbrrDTDCpoXephuzyj9WR/XhPJVPv0/+bzRrPSsmPgcgYkruDkgkqFalCiagDAO3aK3JAlezPOZlGkebWCobkccBFQaiWVUDr++7VWdSotPEkRV9SxPDjlqp/EZQsPaWB6YTXBKWPLGDv5w1wFEtmSG3AHoDTY/ZW7x8a8OPXj30JHfmIkiPUBnl6i0ecgljdyjXFLA2GDsdhcjTwTQg4AgoAy81TGRtbBfnmdKp5pIfQAnAYojjuYD+JLyabG8VK2ppfJs6AFzPX5+aNVqWkTaxru02SH7bVHIICPxZUg4rnHC39mGhiK4HlrusMKb9qaiubjteMWMAzoli8Hyv+P2w4pm0DI2PVVt+GsqRjR6kpPPFaa+51c6pdPjgwr75Bfl21dZprs1WOD/Gdi5pjgQtNKlAxeNc1tkGKZGfQSnAcxcwih7Do/Z8Ie/1fBb3kd8d1HjVQyLmAgVZhgkqrN08HtoGh4AsuiJf2C3n2E/L8DO7j7JAc54skbnoJ6MewhH0yO1hhPYY=
  - secure: S7P9v242ZXaGpSUnQZ68BggZR5FcwCx7mSf3kp9Notu5VEmtfsAJqBebieCiE8IllJ3/6+c4KOxi/bBoi19GxU+oIA0kKIUrXyO4w9nF8vgXI7kSw2nMeZok/vTd9UFjR6ycj78vjzerZUYfNDaj3vrAlfGrIH6pOmjhFBRq/JL+Ez/y53ralWlixWXCpxvx5YUZcLCqN1aATpDbgXUefZ8OWfSfw+a/NLInvgiONnkpt+2A/SLNKY1HcIsE3hg9OAnk9aaSHfJfdNk/tNYWZKRXFRZ+4+XNnqyLNhDpuW1afVnNLoBqsP65c13AIMd3oiRr1lDZK747DrDhm45TIHVg+M4MxUZFyj5tR/lzS1t738/oFGqnIM2gYN/nhC5Pq29H85BQgWG+/vQCGXK0xEdsv9PGiK+v82guI1kf8cR5x9rsztWeq+5zm5ByXfYyd5l0uxDG3BrU50Q7j0XIIid/WI8lNIMnqnC9caPaZsa+PVW2OJ1Ol9pg26yKgBteQ4EEYv48N7WsGzid1KUQ2jkfh/PNpg7zJ3HdRKpc/UNmfP6arLNC24sHL/2wr41X01HaNiXQ3N5nPyZK9co14+L8OIBILTrQ5E81xzQdpDApYAnpshIn5+EwHbdlU9jMPLv+bR6qOjsY6W8hvmr8VKPSyCzCoC1//dTbK9iyGIw=
before_install:
- openssl aes-256-cbc -K $encrypted_639fe5e43c1b_key -iv $encrypted_639fe5e43c1b_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine ~/.ssh/google_compute_engine
