---
# handlers file for db
- name: enable mongod
  systemd: name=mongod enabled=yes

- name: start mongod
  systemd: name=mongod state=started

- name: restart mongod
  systemd: name=mongod state=restarted
