---
dependency:
  name: galaxy
lint:
  name: yamllint
driver:
  name: gce
vars:
  ssh_user: slav
  ssh_identity_file: /home/slav/.ssh/slav
platforms:
  - name: instance-travis
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20170919
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
